/*
 * M3ScaleBilling.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/17/2016
 */
using System;
using System.Linq;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using M3ScaleBilling.PCL;

namespace M3ScaleBilling.PCL.Models
{
    [JsonConverter(typeof(StringValuedEnumConverter))]
    public enum StateEnum
    {
        OPEN, //TODO: Write general description for this method
        PENDING, //TODO: Write general description for this method
        PAID, //TODO: Write general description for this method
        UNPAID, //TODO: Write general description for this method
        CANCELLED, //TODO: Write general description for this method
    }

    /// <summary>
    /// Helper for the enum type StateEnum
    /// </summary>
    public static class StateEnumHelper
    {
        //string values corresponding the enum elements
        private static List<string> stringValues = new List<string> { "open", "pending", "paid", "unpaid", "cancelled" };

        /// <summary>
        /// Converts a StateEnum value to a corresponding string value
        /// </summary>
        /// <param name="enumValue">The StateEnum value to convert</param>
        /// <returns>The representative string value</returns>
        public static string ToValue(StateEnum enumValue)
        {
            switch(enumValue)
            {
                //only valid enum elements can be used
                //this is necessary to avoid errors
                case StateEnum.OPEN:
                case StateEnum.PENDING:
                case StateEnum.PAID:
                case StateEnum.UNPAID:
                case StateEnum.CANCELLED:
                    return stringValues[(int)enumValue];

                //an invalid enum value was requested
                default:
                    return null;
            }
        }

        /// <summary>
        /// Convert a list of StateEnum values to a list of strings
        /// </summary>
        /// <param name="enumValues">The list of StateEnum values to convert</param>
        /// <returns>The list of representative string values</returns>
        public static List<string> ToValue(List<StateEnum> enumValues)
        {
            if (null == enumValues)
                return null;

            return enumValues.Select(eVal => ToValue(eVal)).ToList();
        }

        /// <summary>
        /// Converts a string value into StateEnum value
        /// </summary>
        /// <param name="value">The string value to parse</param>
        /// <returns>The parsed StateEnum value</returns>
        public static StateEnum ParseString(string value)
        {
            int index = stringValues.IndexOf(value);
            if(index < 0)
                throw new InvalidCastException(string.Format("Unable to cast value: {0} to type StateEnum", value));

            return (StateEnum) index;
        }
    }
} 