/*
 * M3ScaleBilling.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/17/2016
 */
using System;
using M3ScaleBilling.PCL.Controllers;
using M3ScaleBilling.PCL.Http.Client;

namespace M3ScaleBilling.PCL
{
    public partial class M3ScaleBillingClient
    {

        /// <summary>
        /// Singleton access to Finance controller
        /// </summary>
        public FinanceController Finance
        {
            get
            {
                return FinanceController.Instance;
            }
        }
        /// <summary>
        /// The shared http client to use for all API calls
        /// </summary>
        public IHttpClient SharedHttpClient
        {
            get
            {
                return BaseController.ClientInstance;
            }
            set
            {
                BaseController.ClientInstance = value;
            }        
        }
        
        /// <summary>
        /// Default constructor
        /// </summary>
        public M3ScaleBillingClient() { }
    }
}